require 'spec_helper'

describe Jade::Renderer do

  context 'users/index' do
    it 'render users index page' do
      get '/users'
      response.should render_template(:index)
    end

    it 'renders the template HTML' do
      get '/users'
      response.body.should include '<h1>Hello All Users</h1>'
    end
  end

  context 'users/show' do

    before :each do
      @user = stub_model(User, :name => 'Sam', :email => 'sam@gmail.com')
      User.should_receive(:find).and_return(@user)
    end

    it 'renders instance variables' do
      get user_path(@user)
      response.body.should include 'My name is %s' % @user.name
    end

    it 'renders HTML generated by application mixin' do
      get user_path(@user)
      response.body.should include @user.name.downcase
    end

    it 'renders HTML generated by users mixin' do
      get user_path(@user)
      response.body.should include @user.email.upcase
    end
  end
end